import type { Bundle, GeneratedFile } from "../datapack/types";
import { toPortableBingo } from "./portable";
import type { ValidationResult } from "../datapack/validate";
import type { BingoConfig } from "./board";
import { centerIndex, bingoLines } from "./board";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { validateDatapack } from "../datapack/validate";
import { findTrigger, describeObjective } from "../objective/triggers";
import { compileRewardLines } from "../reward/actions";

export interface BingoGenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  datapackFileName: string;
}

const WIN_OBJ = "bingo"; // per-player flag: a line has been rewarded
const BLACKOUT_OBJ = "bingo_bo"; // per-player flag: blackout rewarded

/** Selector advancement filter for a set of cell ids, e.g. {ns:cell_0=true,...}. */
function advFilter(namespace: string, indices: number[]): string {
  return `{${indices.map((i) => `${namespace}:cell_${i}=true`).join(",")}}`;
}

/**
 * Compile a bingo board into a tick-free datapack:
 *  - each non-free cell -> an advancement (Cobblemon trigger) + a function that
 *    runs the line check when that cell completes
 *  - check.mcfunction tests every line via @s[advancements={...}] and, the first
 *    time a line (or the whole board) is complete, runs win / blackout
 *  - load creates the two flag objectives; uninstall resets them
 */
export function generateBingo(config: BingoConfig): BingoGenerateResult {
  const slug = toId(config.title || "bingo");
  const ns = toNamespace(config.title || "owner_bingo");
  const center = centerIndex(config.size, config.freeCenter);

  const autoIndices = config.cells
    .map((o, i) => ({ o, i }))
    .filter(({ o, i }) => i !== center && o.mode === "auto" && findTrigger(o.triggerId))
    .map(({ i }) => i);

  const files: GeneratedFile[] = [
    buildPackMeta({ description: `${config.title} — Bingo, generated by Cobbleverse Event Forge`, packFormat: config.packFormat }),
  ];

  // per-cell advancement + function
  for (const i of autoIndices) {
    const cell = config.cells[i];
    const t = findTrigger(cell.triggerId)!;
    files.push({
      path: `data/${ns}/advancement/cell_${i}.json`,
      contents: JSON.stringify(
        {
          criteria: { done: { trigger: t.id, conditions: t.conditions(cell) } },
          requirements: [["done"]],
          rewards: { function: `${ns}:cell_${i}` },
        },
        null,
        2,
      ),
      kind: "advancement",
      label: `cell ${i} advancement`,
    });
    files.push({
      path: `data/${ns}/function/cell_${i}.mcfunction`,
      contents:
        [
          `# Bingo cell ${i}: ${describeObjective(cell)}`,
          `tellraw @s ${JSON.stringify({ text: `Bingo square done: ${describeObjective(cell)}`, color: "aqua" })}`,
          `function ${ns}:check`,
          "",
        ].join("\n"),
      kind: "function",
      label: `cell_${i}.mcfunction`,
    });
  }

  // check: test every line, then (optionally) blackout
  const lines = bingoLines(config.size, center).map((line) => line.filter((i) => autoIndices.includes(i)));
  const check: string[] = [`# Run after any cell completes; rewards the first bingo line / blackout.`];
  for (const line of lines) {
    if (line.length === 0) continue;
    check.push(
      `execute if entity @s[advancements=${advFilter(ns, line)}] unless score @s ${WIN_OBJ} matches 1 run function ${ns}:win`,
    );
  }
  if (config.blackoutReward.length && autoIndices.length) {
    check.push(
      `execute if entity @s[advancements=${advFilter(ns, autoIndices)}] unless score @s ${BLACKOUT_OBJ} matches 1 run function ${ns}:blackout`,
    );
  }
  check.push("");
  files.push({ path: `data/${ns}/function/check.mcfunction`, contents: check.join("\n"), kind: "function", label: "check.mcfunction" });

  // win
  files.push({
    path: `data/${ns}/function/win.mcfunction`,
    contents: [
      `# First completed bingo line.`,
      `scoreboard players set @s ${WIN_OBJ} 1`,
      ...compileRewardLines(config.bingoReward, { packFormat: config.packFormat }),
      `tellraw @a ${JSON.stringify([{ selector: "@s" }, { text: " hit BINGO! 🎉", color: "gold" }])}`,
      "",
    ].join("\n"),
    kind: "function",
    label: "win.mcfunction",
  });

  // blackout (optional)
  if (config.blackoutReward.length) {
    files.push({
      path: `data/${ns}/function/blackout.mcfunction`,
      contents: [
        `# Whole board complete.`,
        `scoreboard players set @s ${BLACKOUT_OBJ} 1`,
        ...compileRewardLines(config.blackoutReward, { packFormat: config.packFormat }),
        `tellraw @a ${JSON.stringify([{ selector: "@s" }, { text: " completed the ENTIRE bingo board! 🏆", color: "light_purple" }])}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "blackout.mcfunction",
    });
  }

  // lifecycle: create flag objectives on load, reset on uninstall
  files.push({
    path: `data/${ns}/function/load.mcfunction`,
    contents: [
      `# Bingo: ${config.title}`,
      `scoreboard objectives add ${WIN_OBJ} dummy`,
      `scoreboard objectives add ${BLACKOUT_OBJ} dummy`,
      "",
    ].join("\n"),
    kind: "function",
    label: "load.mcfunction",
  });
  files.push({
    path: `data/minecraft/tags/function/load.json`,
    contents: JSON.stringify({ values: [`${ns}:load`] }, null, 2),
    kind: "tag",
    label: "load tag",
  });
  files.push({
    path: `data/${ns}/function/uninstall.mcfunction`,
    contents: [
      `# Reset this bingo's progress, then delete the datapack.`,
      `scoreboard players reset @a ${WIN_OBJ}`,
      `scoreboard players reset @a ${BLACKOUT_OBJ}`,
      "",
    ].join("\n"),
    kind: "function",
    label: "uninstall.mcfunction",
  });

  const validation = validateDatapack(files);

  // side-car: a printable board
  files.push(buildBoardSheet(config, center));
  // re-importable snapshot of this board — drop it back into the page to edit/re-run later
  files.push({ path: "bingo_config.json", contents: toPortableBingo(config), kind: "readme", label: "bingo_config.json" });

  return {
    bundle: { slug, title: config.title, namespace: ns, packFormat: config.packFormat, files },
    validation,
    datapackFileName: `${slug}.zip`,
  };
}

function buildBoardSheet(config: BingoConfig, center: number): GeneratedFile {
  const L: string[] = [`# 🎲 ${config.title} — Bingo Board`, "", `Complete a full row, column, or diagonal for **BINGO**.`, ""];
  for (let r = 0; r < config.size; r++) {
    const row = [];
    for (let c = 0; c < config.size; c++) {
      const i = r * config.size + c;
      row.push(i === center ? "⭐ FREE" : describeObjective(config.cells[i]));
    }
    L.push("| " + row.join(" | ") + " |");
    if (r === 0) L.push("|" + " --- |".repeat(config.size));
  }
  L.push("");
  return { path: "bingo_board.md", contents: L.join("\n") + "\n", kind: "readme", label: "bingo_board.md" };
}
