import type { Bundle, GeneratedFile } from "../datapack/types";
import type { ValidationResult } from "../datapack/validate";
import type { FeaturedMon } from "../event/types";
import type { SafariConfig } from "./types";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { buildSpawnFiles } from "../datapack/spawns";
import { validateDatapack } from "../datapack/validate";
import { usableGiveCommand, consumeAdvancement } from "../datapack/usableItem";
import { buildObjectiveFiles } from "../objective/generate";
import { newObjective } from "../objective/types";
import { buildRulesBoard, buildNpcDialogue, buildSignText, buildSafariDiscord, buildSafariChecklist } from "./text";

export interface SafariGenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  datapackFileName: string;
}

const SAFARI_DATA_KEY = "safari";

/** Build the tiered featured-mon list (common / rare / ultra-rare). */
function tieredFeatured(config: SafariConfig): FeaturedMon[] {
  const tiers: [string[], FeaturedMon["bucket"], number, string][] = [
    [config.common, "common", 50, "10-30"],
    [config.rare, "rare", 8, "20-40"],
    [config.ultraRare, "ultra-rare", 1, "30-55"],
  ];
  return tiers.flatMap(([list, bucket, weight, level]) =>
    list.filter((s) => s.trim()).map((species) => ({ species, bucket, weight, level })),
  );
}

export function generateSafari(config: SafariConfig): SafariGenerateResult {
  const slug = toId(config.title || "safari");
  const ns = toNamespace(config.title || "owner_safari");

  const datapackFiles: GeneratedFile[] = [
    buildPackMeta({ description: `${config.title} — Safari Zone, generated by Cobbleverse Event Forge`, packFormat: config.packFormat }),
    ...buildSpawnFiles({ namespace: ns, eventSlug: slug, weather: config.weather, featured: tieredFeatured(config), biomes: config.biomes }),
  ];

  // --- entry ticket (usable item -> enter function) ---
  if (config.ticket.enabled) {
    const enterId = `${ns}:enter_${slug}`;
    datapackFiles.push({
      path: `data/${ns}/advancement/use_${slug}.json`,
      contents: JSON.stringify(
        consumeAdvancement({ baseItem: config.ticket.baseItem, dataKey: SAFARI_DATA_KEY, dataValue: slug, rewardFunctionId: enterId }),
        null,
        2,
      ),
      kind: "advancement",
      label: "use-ticket advancement",
    });
    datapackFiles.push({
      path: `data/${ns}/function/enter_${slug}.mcfunction`,
      contents: [
        `# Runs when a player uses the ${config.title} ticket.`,
        `tellraw @s ${JSON.stringify([{ text: "Welcome to the ", color: "green" }, { text: config.title, color: "gold" }, { text: "!", color: "green" }])}`,
        `tellraw @s ${JSON.stringify({ text: `You have ${config.timeLimitMinutes} minutes. Rules: ${config.rules.join("; ")}`, color: "gray" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "enter.mcfunction",
    });
    const give = usableGiveCommand({
      baseItem: config.ticket.baseItem,
      name: `${config.title} Ticket`,
      nameColor: "green",
      lore: "Right-click & hold to enter the zone",
      glint: config.ticket.glint,
      consumeSeconds: 0.6,
      dataKey: SAFARI_DATA_KEY,
      dataValue: slug,
      packFormat: config.packFormat,
    });
    datapackFiles.push({
      path: `data/${ns}/function/give_${slug}_ticket.mcfunction`,
      contents: [
        `# Give one ${config.title} entry ticket:`,
        `#   /execute as <player> run function ${ns}:give_${slug}_ticket`,
        give,
        `tellraw @s ${JSON.stringify({ text: `You received a ${config.title} ticket!`, color: "gold" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "give_ticket.mcfunction",
    });
  }

  // --- reward objective (catch N of a type) ---
  if (config.reward.enabled) {
    const typeStr = config.reward.type === "any" ? "Pokémon" : `${config.reward.type}-type`;
    const obj = newObjective("reward", {
      mode: "auto",
      triggerId: "cobblemon:catch_pokemon",
      count: config.reward.count,
      pokemonType: config.reward.type,
      announce: true,
      label: `Catch ${config.reward.count} ${typeStr} in the ${config.title}`,
      rewards: config.reward.rewards,
    });
    datapackFiles.push(...buildObjectiveFiles({ namespace: ns, objectives: [obj], packFormat: config.packFormat }));
  }

  const validation = validateDatapack(datapackFiles);
  const datapackFileName = `${slug}.zip`;

  const sideCars: GeneratedFile[] = [
    buildRulesBoard(config),
    buildNpcDialogue(config),
    buildSignText(config),
    buildSafariDiscord(config),
    buildSafariChecklist({ config, namespace: ns, slug, datapackFileName, validation }),
  ];

  return {
    bundle: { slug, title: config.title, namespace: ns, packFormat: config.packFormat, files: [...datapackFiles, ...sideCars] },
    validation,
    datapackFileName,
  };
}
