import type { Bundle, GeneratedFile } from "../datapack/types";
import type { ValidationResult } from "../datapack/validate";
import type { FeaturedMon } from "../event/types";
import type { SafariConfig } from "./types";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { buildSpawnFiles } from "../datapack/spawns";
import { validateDatapack } from "../datapack/validate";
import { usableGiveCommand, consumeAdvancement } from "../datapack/usableItem";
import { buildObjectiveFiles } from "../objective/generate";
import { newObjective } from "../objective/types";
import { buildRulesBoard, buildNpcDialogue, buildSignText, buildSafariDiscord, buildSafariChecklist } from "./text";

export interface SafariGenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  datapackFileName: string;
}

const SAFARI_DATA_KEY = "safari";
const TIMER_OBJ = "safari_time";

/** Build the tiered featured-mon list (common / rare / ultra-rare). */
function tieredFeatured(config: SafariConfig): FeaturedMon[] {
  const tiers: [string[], FeaturedMon["bucket"], number, string][] = [
    [config.common, "common", 50, "10-30"],
    [config.rare, "rare", 8, "20-40"],
    [config.ultraRare, "ultra-rare", 1, "30-55"],
  ];
  return tiers.flatMap(([list, bucket, weight, level]) =>
    list.filter((s) => s.trim()).map((species) => ({ species, bucket, weight, level })),
  );
}

export function generateSafari(config: SafariConfig): SafariGenerateResult {
  const slug = toId(config.title || "safari");
  const ns = toNamespace(config.title || "owner_safari");

  const datapackFiles: GeneratedFile[] = [
    buildPackMeta({ description: `${config.title} — Safari Zone, generated by Cobbleverse Event Forge`, packFormat: config.packFormat }),
    ...buildSpawnFiles({ namespace: ns, eventSlug: slug, weather: config.weather, featured: tieredFeatured(config), biomes: config.biomes }),
  ];

  // commands collected for the (optional) load + uninstall functions
  const loadLines: string[] = [];
  const uninstallLines: string[] = [];

  // --- temporary arena world (Resource World mod) ---
  if (config.arena.enabled) {
    const singleBiome = config.arena.mode === "single-biome";
    // For single-biome, define a one-biome overworld dimension and mirror THAT,
    // so the whole arena is the safari's biome.
    let mirrorTarget = config.arena.mirror.trim() || "minecraft:overworld";
    if (singleBiome) {
      const biome = config.arena.biome.trim() || "minecraft:plains";
      mirrorTarget = `${ns}:zone`;
      datapackFiles.push({
        path: `data/${ns}/dimension/zone.json`,
        contents: JSON.stringify(
          {
            type: "minecraft:overworld",
            generator: {
              type: "minecraft:noise",
              settings: "minecraft:overworld",
              biome_source: { type: "minecraft:fixed", biome },
            },
          },
          null,
          2,
        ),
        kind: "dimension",
        label: "single-biome dimension",
      });
    }
    datapackFiles.push({
      path: `data/${ns}/function/create_arena.mcfunction`,
      contents: [
        `# Create the temporary "${config.title}" arena world (Resource World mod).`,
        `# Run this ONCE during setup. Syntax may vary by mod version:`,
        `#   /resourceworld create <id> mirror <dimension> [seed]`,
        ...(singleBiome
          ? [
              `# Mirrors the single-biome dimension ${mirrorTarget} defined by this pack.`,
              `# IMPORTANT: that dimension only registers after a FULL SERVER RESTART`,
              `# (datapack dimensions do NOT load on /reload). Restart once with this`,
              `# pack installed, THEN run this function — otherwise you'll get`,
              `# "Missing key ... ${mirrorTarget}".`,
            ]
          : []),
        `resourceworld create ${slug} mirror ${mirrorTarget}`,
        `tellraw @a ${JSON.stringify({ text: `${config.title} arena world created — players enter with a ticket.`, color: "green" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "create_arena.mcfunction",
    });
    uninstallLines.push(`resourceworld delete ${slug}`);
  }

  // --- per-player countdown timer (1s self-rescheduling loop) ---
  if (config.timer.enabled) {
    const total = Math.max(1, Math.round(config.timeLimitMinutes)) * 60; // seconds
    loadLines.push(`scoreboard objectives add ${TIMER_OBJ} dummy`);
    uninstallLines.push(`scoreboard players reset @a ${TIMER_OBJ}`);

    const tick: string[] = [
      `# Safari countdown — runs once per second, only while players are inside.`,
      `scoreboard players remove @a[scores={${TIMER_OBJ}=1..}] ${TIMER_OBJ} 1`,
    ];
    const warnSeconds = config.timer.warnings
      .filter((m, i, arr) => arr.indexOf(m) === i)
      .filter((m) => m > 0 && m * 60 < total)
      .sort((a, b) => b - a);
    for (const m of warnSeconds) {
      const s = m * 60;
      const msg = `⏳ ${m} minute${m === 1 ? "" : "s"} left in the ${config.title}!`;
      tick.push(`execute as @a[scores={${TIMER_OBJ}=${s}}] at @s run tellraw @s ${JSON.stringify({ text: msg, color: "yellow" })}`);
      tick.push(`execute as @a[scores={${TIMER_OBJ}=${s}}] at @s run playsound minecraft:block.note_block.bell player @s ~ ~ ~ 1 1`);
    }
    tick.push(`# time's up — send each expired player home`);
    tick.push(`execute as @a[scores={${TIMER_OBJ}=0}] at @s run function ${ns}:safari_home`);
    tick.push(`# keep the loop alive only while someone still has time left`);
    tick.push(`execute if entity @a[scores={${TIMER_OBJ}=1..}] run schedule function ${ns}:safari_tick 1s replace`);
    tick.push("");
    datapackFiles.push({
      path: `data/${ns}/function/safari_tick.mcfunction`,
      contents: tick.join("\n"),
      kind: "function",
      label: "safari_tick.mcfunction",
    });

    datapackFiles.push({
      path: `data/${ns}/function/safari_home.mcfunction`,
      contents: [
        `# Return a player home when their safari time runs out.`,
        `tellraw @s ${JSON.stringify({ text: `⌛ Your time in the ${config.title} is up — heading home!`, color: "red" })}`,
        `resourceworld home`,
        `scoreboard players reset @s ${TIMER_OBJ}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "safari_home.mcfunction",
    });
  }

  // --- entry ticket (usable item -> enter function) ---
  if (config.ticket.enabled) {
    const enterId = `${ns}:enter_${slug}`;
    datapackFiles.push({
      path: `data/${ns}/advancement/use_${slug}.json`,
      contents: JSON.stringify(
        consumeAdvancement({ baseItem: config.ticket.baseItem, dataKey: SAFARI_DATA_KEY, dataValue: slug, rewardFunctionId: enterId }),
        null,
        2,
      ),
      kind: "advancement",
      label: "use-ticket advancement",
    });
    datapackFiles.push({
      path: `data/${ns}/function/enter_${slug}.mcfunction`,
      contents: [
        `# Runs when a player uses the ${config.title} ticket.`,
        `tellraw @s ${JSON.stringify([{ text: "Welcome to the ", color: "green" }, { text: config.title, color: "gold" }, { text: "!", color: "green" }])}`,
        ...(config.safariBalls > 0
          ? [
              `# Safari Balls (1.5x catch rate) — the in-zone catch boost`,
              `give @s cobblemon:safari_ball ${Math.round(config.safariBalls)}`,
              `tellraw @s ${JSON.stringify({ text: `Here are ${Math.round(config.safariBalls)} Safari Balls — they catch 1.5× better. Make them count!`, color: "aqua" })}`,
            ]
          : []),
        `tellraw @s ${JSON.stringify({ text: `You have ${config.timeLimitMinutes} minutes. Rules: ${config.rules.join("; ")}`, color: "gray" })}`,
        ...(config.timer.enabled
          ? [
              `# start the countdown and kick off the 1s loop`,
              `scoreboard players set @s ${TIMER_OBJ} ${Math.max(1, Math.round(config.timeLimitMinutes)) * 60}`,
              `schedule function ${ns}:safari_tick 1s replace`,
            ]
          : []),
        ...(config.arena.enabled
          ? [`# warp the player into the temporary arena world`, `resourceworld tp ${slug}`]
          : []),
        "",
      ].join("\n"),
      kind: "function",
      label: "enter.mcfunction",
    });
    const give = usableGiveCommand({
      baseItem: config.ticket.baseItem,
      name: `${config.title} Ticket`,
      nameColor: "green",
      lore: "Right-click & hold to enter the zone",
      glint: config.ticket.glint,
      consumeSeconds: 0.6,
      dataKey: SAFARI_DATA_KEY,
      dataValue: slug,
      packFormat: config.packFormat,
    });
    datapackFiles.push({
      path: `data/${ns}/function/give_${slug}_ticket.mcfunction`,
      contents: [
        `# Give one ${config.title} entry ticket:`,
        `#   /execute as <player> run function ${ns}:give_${slug}_ticket`,
        give,
        `tellraw @s ${JSON.stringify({ text: `You received a ${config.title} ticket!`, color: "gold" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "give_ticket.mcfunction",
    });
  }

  // --- reward objective (catch N of a type) ---
  if (config.reward.enabled) {
    const typeStr = config.reward.type === "any" ? "Pokémon" : `${config.reward.type}-type`;
    const obj = newObjective("reward", {
      mode: "auto",
      triggerId: "cobblemon:catch_pokemon",
      count: config.reward.count,
      pokemonType: config.reward.type,
      announce: true,
      label: `Catch ${config.reward.count} ${typeStr} in the ${config.title}`,
      rewards: config.reward.rewards,
    });
    datapackFiles.push(...buildObjectiveFiles({ namespace: ns, objectives: [obj], packFormat: config.packFormat }));
  }

  // --- load (objective setup) + uninstall (teardown), if anything needs them ---
  if (loadLines.length) {
    datapackFiles.push({
      path: `data/${ns}/function/load.mcfunction`,
      contents: [`# Load setup for ${config.title}.`, ...loadLines, ""].join("\n"),
      kind: "function",
      label: "load.mcfunction",
    });
    datapackFiles.push({
      path: `data/minecraft/tags/function/load.json`,
      contents: JSON.stringify({ values: [`${ns}:load`] }, null, 2),
      kind: "tag",
      label: "load tag",
    });
  }
  if (uninstallLines.length) {
    datapackFiles.push({
      path: `data/${ns}/function/uninstall.mcfunction`,
      contents: [
        `# Tear down the "${config.title}" safari, then remove the datapack and /reload.`,
        ...uninstallLines,
        `tellraw @a ${JSON.stringify({ text: `${config.title} torn down.`, color: "gray" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "uninstall.mcfunction",
    });
  }

  const validation = validateDatapack(datapackFiles);
  const datapackFileName = `${slug}.zip`;

  const sideCars: GeneratedFile[] = [
    buildRulesBoard(config),
    buildNpcDialogue(config),
    buildSignText(config),
    buildSafariDiscord(config),
    buildSafariChecklist({ config, namespace: ns, slug, datapackFileName, validation }),
  ];

  return {
    bundle: { slug, title: config.title, namespace: ns, packFormat: config.packFormat, files: [...datapackFiles, ...sideCars] },
    validation,
    datapackFileName,
  };
}
