import type { Bundle, GeneratedFile } from "../datapack/types";
import type { ValidationResult } from "../datapack/validate";
import type { FeaturedMon } from "../event/types";
import type { SafariConfig } from "./types";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { buildSpawnFiles } from "../datapack/spawns";
import { validateDatapack } from "../datapack/validate";
import { usableGiveCommand, consumeAdvancement } from "../datapack/usableItem";
import { buildObjectiveFiles } from "../objective/generate";
import { newObjective } from "../objective/types";
import { buildRulesBoard, buildNpcDialogue, buildSignText, buildSafariDiscord, buildSafariChecklist } from "./text";

export interface SafariGenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  datapackFileName: string;
}

const SAFARI_DATA_KEY = "safari";
const TIMER_OBJ = "safari_time";
// Per-player capture of where a player entered from, so they return there on exit.
const RET_X = "safari_ret_x";
const RET_Y = "safari_ret_y";
const RET_Z = "safari_ret_z";

/** Build the tiered featured-mon list (common / rare / ultra-rare). */
function tieredFeatured(config: SafariConfig): FeaturedMon[] {
  const tiers: [string[], FeaturedMon["bucket"], number, string][] = [
    [config.common, "common", 50, "10-30"],
    [config.rare, "rare", 8, "20-40"],
    [config.ultraRare, "ultra-rare", 1, "30-55"],
  ];
  return tiers.flatMap(([list, bucket, weight, level]) =>
    list.filter((s) => s.trim()).map((species) => ({ species, bucket, weight, level })),
  );
}

export function generateSafari(config: SafariConfig): SafariGenerateResult {
  const slug = toId(config.title || "safari");
  const ns = toNamespace(config.title || "owner_safari");

  const datapackFiles: GeneratedFile[] = [
    buildPackMeta({ description: `${config.title} — Safari Zone, generated by Cobbleverse Event Forge`, packFormat: config.packFormat }),
    ...buildSpawnFiles({ namespace: ns, eventSlug: slug, weather: config.weather, featured: tieredFeatured(config), biomes: config.biomes }),
  ];

  // commands collected for the (optional) load + uninstall functions
  const loadLines: string[] = [];
  const uninstallLines: string[] = [];

  // --- arena dimension (datapack-defined; entered with vanilla teleports) ---
  // We deliberately do NOT use the Resource World mod: its tp/home commands only
  // work when typed live, not when a datapack function runs them, so a ticket could
  // never warp players in. Instead we define a standalone dimension here and move
  // players with vanilla `execute in <dim> run …`, which runs fine from a function
  // at permission level 2 and (because the dimension exists at login) avoids the
  // client desync. The dimension only registers after a FULL SERVER RESTART
  // (datapack dimensions do NOT load on /reload).
  if (config.arena.enabled) {
    const singleBiome = config.arena.mode === "single-biome";
    const biome = config.arena.biome.trim() || "minecraft:plains";
    const arenaDim = `${ns}:zone`;
    datapackFiles.push({
      path: `data/${ns}/dimension/zone.json`,
      contents: JSON.stringify(
        {
          type: "minecraft:overworld",
          generator: {
            type: "minecraft:noise",
            settings: "minecraft:overworld",
            // single-biome → the whole arena is the safari's biome; otherwise a
            // normal (but separate) overworld.
            biome_source: singleBiome
              ? { type: "minecraft:fixed", biome }
              : { type: "minecraft:multi_noise", preset: "minecraft:overworld" },
          },
        },
        null,
        2,
      ),
      kind: "dimension",
      label: "arena dimension",
    });
    // Per-player return point — captured on entry so each player goes back to their
    // OWN spot, never a shared one.
    loadLines.push(
      `scoreboard objectives add ${RET_X} dummy`,
      `scoreboard objectives add ${RET_Y} dummy`,
      `scoreboard objectives add ${RET_Z} dummy`,
    );
    uninstallLines.push(
      `scoreboard players reset @a ${RET_X}`,
      `scoreboard players reset @a ${RET_Y}`,
      `scoreboard players reset @a ${RET_Z}`,
    );
    // Warp IN: drop ONLY this player (@s) on a safe surface within 200 blocks of
    // (0,0) in the arena dimension. Pure vanilla, so it runs from the ticket's
    // reward function with no mod command and no op level needed.
    datapackFiles.push({
      path: `data/${ns}/function/warp_${slug}.mcfunction`,
      contents: [
        `# Teleport one player (@s) into the arena dimension.`,
        `execute in ${arenaDim} run spreadplayers 0 0 1 200 false @s`,
        "",
      ].join("\n"),
      kind: "function",
      label: "warp.mcfunction",
    });
    // Warp BACK: return the player to exactly where they entered from (captured into
    // the scoreboard on entry). Copied per-player into storage, then a macro feeds
    // the coords to tp. Assumes players enter from the overworld (where tickets live).
    datapackFiles.push({
      path: `data/${ns}/function/return_${slug}.mcfunction`,
      contents: [
        `# Send @s back to their captured entry point in the overworld.`,
        `execute store result storage ${ns}:return x int 1 run scoreboard players get @s ${RET_X}`,
        `execute store result storage ${ns}:return y int 1 run scoreboard players get @s ${RET_Y}`,
        `execute store result storage ${ns}:return z int 1 run scoreboard players get @s ${RET_Z}`,
        `function ${ns}:do_return_${slug} with storage ${ns}:return`,
        "",
      ].join("\n"),
      kind: "function",
      label: "return.mcfunction",
    });
    datapackFiles.push({
      path: `data/${ns}/function/do_return_${slug}.mcfunction`,
      contents: [
        `# Macro tp to the captured return coords (filled in by return_${slug}).`,
        `$execute in minecraft:overworld run tp @s $(x) $(y) $(z)`,
        "",
      ].join("\n"),
      kind: "function",
      label: "do_return.mcfunction",
    });
  }

  // --- per-player countdown timer (1s self-rescheduling loop) ---
  if (config.timer.enabled) {
    const total = Math.max(1, Math.round(config.timeLimitMinutes)) * 60; // seconds
    loadLines.push(`scoreboard objectives add ${TIMER_OBJ} dummy`);
    uninstallLines.push(`scoreboard players reset @a ${TIMER_OBJ}`);

    const tick: string[] = [
      `# Safari countdown — runs once per second, only while players are inside.`,
      `scoreboard players remove @a[scores={${TIMER_OBJ}=1..}] ${TIMER_OBJ} 1`,
    ];
    const warnSeconds = config.timer.warnings
      .filter((m, i, arr) => arr.indexOf(m) === i)
      .filter((m) => m > 0 && m * 60 < total)
      .sort((a, b) => b - a);
    for (const m of warnSeconds) {
      const s = m * 60;
      const msg = `⏳ ${m} minute${m === 1 ? "" : "s"} left in the ${config.title}!`;
      tick.push(`execute as @a[scores={${TIMER_OBJ}=${s}}] at @s run tellraw @s ${JSON.stringify({ text: msg, color: "yellow" })}`);
      tick.push(`execute as @a[scores={${TIMER_OBJ}=${s}}] at @s run playsound minecraft:block.note_block.bell player @s ~ ~ ~ 1 1`);
    }
    tick.push(`# time's up — send each expired player home`);
    tick.push(`execute as @a[scores={${TIMER_OBJ}=0}] at @s run function ${ns}:safari_home`);
    tick.push(`# keep the loop alive only while someone still has time left`);
    tick.push(`execute if entity @a[scores={${TIMER_OBJ}=1..}] run schedule function ${ns}:safari_tick 1s replace`);
    tick.push("");
    datapackFiles.push({
      path: `data/${ns}/function/safari_tick.mcfunction`,
      contents: tick.join("\n"),
      kind: "function",
      label: "safari_tick.mcfunction",
    });

    datapackFiles.push({
      path: `data/${ns}/function/safari_home.mcfunction`,
      contents: [
        `# Return a player home when their safari time runs out.`,
        `tellraw @s ${JSON.stringify({ text: `⌛ Your time in the ${config.title} is up — heading home!`, color: "red" })}`,
        ...(config.arena.enabled ? [`function ${ns}:return_${slug}`] : []),
        `scoreboard players reset @s ${TIMER_OBJ}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "safari_home.mcfunction",
    });
  }

  // --- entry ticket (usable item -> enter function) ---
  if (config.ticket.enabled) {
    const enterId = `${ns}:enter_${slug}`;
    datapackFiles.push({
      path: `data/${ns}/advancement/use_${slug}.json`,
      contents: JSON.stringify(
        consumeAdvancement({ baseItem: config.ticket.baseItem, dataKey: SAFARI_DATA_KEY, dataValue: slug, rewardFunctionId: enterId }),
        null,
        2,
      ),
      kind: "advancement",
      label: "use-ticket advancement",
    });
    datapackFiles.push({
      path: `data/${ns}/function/enter_${slug}.mcfunction`,
      contents: [
        `# Runs when a player uses the ${config.title} ticket.`,
        `tellraw @s ${JSON.stringify([{ text: "Welcome to the ", color: "green" }, { text: config.title, color: "gold" }, { text: "!", color: "green" }])}`,
        ...(config.safariBalls > 0
          ? [
              `# Safari Balls (1.5x catch rate) — the in-zone catch boost`,
              `give @s cobblemon:safari_ball ${Math.round(config.safariBalls)}`,
              `tellraw @s ${JSON.stringify({ text: `Here are ${Math.round(config.safariBalls)} Safari Balls — they catch 1.5× better. Make them count!`, color: "aqua" })}`,
            ]
          : []),
        `tellraw @s ${JSON.stringify({ text: `You have ${config.timeLimitMinutes} minutes. Rules: ${config.rules.join("; ")}`, color: "gray" })}`,
        ...(config.timer.enabled
          ? [
              `# start the countdown and kick off the 1s loop`,
              `scoreboard players set @s ${TIMER_OBJ} ${Math.max(1, Math.round(config.timeLimitMinutes)) * 60}`,
              `schedule function ${ns}:safari_tick 1s replace`,
            ]
          : []),
        ...(config.arena.enabled
          ? [
              `# capture where the player entered from (per-player) so they return to`,
              `# this exact spot on exit, THEN warp them into the arena dimension.`,
              `execute store result score @s ${RET_X} run data get entity @s Pos[0] 1`,
              `execute store result score @s ${RET_Y} run data get entity @s Pos[1] 1`,
              `execute store result score @s ${RET_Z} run data get entity @s Pos[2] 1`,
              `function ${ns}:warp_${slug}`,
            ]
          : []),
        `# re-arm the ticket so it can be used again next time`,
        `advancement revoke @s only ${ns}:use_${slug}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "enter.mcfunction",
    });
    const give = usableGiveCommand({
      baseItem: config.ticket.baseItem,
      name: `${config.title} Ticket`,
      nameColor: "green",
      lore: "Right-click & hold to enter the zone",
      glint: config.ticket.glint,
      consumeSeconds: 0.6,
      dataKey: SAFARI_DATA_KEY,
      dataValue: slug,
      packFormat: config.packFormat,
    });
    datapackFiles.push({
      path: `data/${ns}/function/give_${slug}_ticket.mcfunction`,
      contents: [
        `# Give one ${config.title} entry ticket:`,
        `#   /execute as <player> run function ${ns}:give_${slug}_ticket`,
        give,
        `tellraw @s ${JSON.stringify({ text: `You received a ${config.title} ticket!`, color: "gold" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "give_ticket.mcfunction",
    });
  }

  // --- reward objective (catch N of a type) ---
  if (config.reward.enabled) {
    const typeStr = config.reward.type === "any" ? "Pokémon" : `${config.reward.type}-type`;
    const obj = newObjective("reward", {
      mode: "auto",
      triggerId: "cobblemon:catch_pokemon",
      count: config.reward.count,
      pokemonType: config.reward.type,
      announce: true,
      label: `Catch ${config.reward.count} ${typeStr} in the ${config.title}`,
      rewards: config.reward.rewards,
    });
    datapackFiles.push(...buildObjectiveFiles({ namespace: ns, objectives: [obj], packFormat: config.packFormat }));
  }

  // --- load (objective setup) + uninstall (teardown), if anything needs them ---
  if (loadLines.length) {
    datapackFiles.push({
      path: `data/${ns}/function/load.mcfunction`,
      contents: [`# Load setup for ${config.title}.`, ...loadLines, ""].join("\n"),
      kind: "function",
      label: "load.mcfunction",
    });
    datapackFiles.push({
      path: `data/minecraft/tags/function/load.json`,
      contents: JSON.stringify({ values: [`${ns}:load`] }, null, 2),
      kind: "tag",
      label: "load tag",
    });
  }
  if (uninstallLines.length) {
    datapackFiles.push({
      path: `data/${ns}/function/uninstall.mcfunction`,
      contents: [
        `# Tear down the "${config.title}" safari, then remove the datapack and /reload.`,
        ...uninstallLines,
        // the arena block already prints its own "deleted" message; only add a
        // generic confirmation when there's no arena (e.g. timer-only).
        `tellraw @a ${JSON.stringify({ text: `${config.title} torn down.`, color: "gray" })}`,
        "",
      ].join("\n"),
      kind: "function",
      label: "uninstall.mcfunction",
    });
  }

  const validation = validateDatapack(datapackFiles);
  const datapackFileName = `${slug}.zip`;

  const sideCars: GeneratedFile[] = [
    buildRulesBoard(config),
    buildNpcDialogue(config),
    buildSignText(config),
    buildSafariDiscord(config),
    buildSafariChecklist({ config, namespace: ns, slug, datapackFileName, validation }),
  ];

  return {
    bundle: { slug, title: config.title, namespace: ns, packFormat: config.packFormat, files: [...datapackFiles, ...sideCars] },
    validation,
    datapackFileName,
  };
}
