import type { Bundle, GeneratedFile } from "../datapack/types";
import type { ValidationResult } from "../datapack/validate";
import type { EventConfig, RewardTier } from "./types";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { buildSpawnFiles } from "../datapack/spawns";
import { buildTierFiles, tierFnId, tierHasFunction } from "./tiers";
import { buildLegendaryFiles } from "./legendary";
import { buildObjectiveFiles } from "../objective/generate";
import { buildLifecycleFiles, tracksProgress } from "./lifecycle";
import type { CompletionWiring } from "./lifecycle";
import { buildCompletionFiles } from "./completion";
import { validateDatapack } from "../datapack/validate";
import { buildBountiesFile } from "./bounties";
import { buildDiscordAnnouncement } from "./discord";
import { buildChecklist } from "./checklist";
import { toPortableEvent } from "./portable";

export interface GenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  /** Suggested .zip file name for the datapack. */
  datapackFileName: string;
}

/**
 * The single entry point: EventConfig in, full file bundle + validation out.
 *
 * Order matters for the checklist, which embeds the validation result and the
 * datapack file name, so we build datapack files first, validate, then build the
 * human-facing side-cars.
 */
export function generateEvent(config: EventConfig): GenerateResult {
  const slug = toId(config.title || "untitled_event");
  const namespace = toNamespace(config.title || "owner_event");

  // --- reward-tier auto-grant wiring ---
  // Categorize each tier (that actually compiles to a function) by its award mode.
  const award = (a: RewardTier["award"]) =>
    config.rewardTiers.filter((t) => (t.award ?? "manual") === a && tierHasFunction(t, config.packFormat)).map(tierFnId);
  const completion: CompletionWiring = {
    total: config.objectives.filter((o) => o.mode === "auto").length,
    winnerFns: award("completion-each"),
    championFns: award("completion-first"),
    participationFns: award("participation"),
  };
  const autoTiers = tracksProgress(completion);

  // --- datapack files ---
  const datapackFiles: GeneratedFile[] = [];
  datapackFiles.push(
    buildPackMeta({
      description: `${config.title} — generated by Cobbleverse Event Forge`,
      packFormat: config.packFormat,
    }),
  );
  datapackFiles.push(
    ...buildSpawnFiles({
      namespace,
      eventSlug: slug,
      weather: config.weather,
      featured: config.featured,
    }),
  );
  datapackFiles.push(
    ...buildTierFiles({
      namespace,
      tiers: config.rewardTiers,
      packFormat: config.packFormat,
    }),
  );
  datapackFiles.push(
    ...buildLegendaryFiles({
      namespace,
      eventSlug: slug,
      trigger: config.legendaryTrigger,
      enableFlag: config.pack.enableFlag,
    }),
  );
  datapackFiles.push(
    ...buildObjectiveFiles({
      namespace,
      objectives: config.objectives,
      packFormat: config.packFormat,
      completion: autoTiers ? { slug } : undefined,
    }),
  );
  if (autoTiers) {
    datapackFiles.push(...buildCompletionFiles({ namespace, slug, title: config.title, completion }));
  }
  // lifecycle (load / uninstall / tick + tags) — centralized so there's one
  // load.json and tick.json only ever appears when explicitly enabled.
  const serverWideLegendary =
    config.legendaryTrigger.enabled &&
    config.legendaryTrigger.legendary.trim() !== "" &&
    config.legendaryTrigger.scope === "server-wide";
  datapackFiles.push(
    ...buildLifecycleFiles({
      namespace,
      slug,
      title: config.title,
      options: config.pack,
      serverWideLegendary,
      completion: autoTiers ? completion : undefined,
    }),
  );

  const validation = validateDatapack(datapackFiles);
  const datapackFileName = `${slug}.zip`;

  // --- side-car files ---
  const sideCars: GeneratedFile[] = [
    buildBountiesFile({ eventSlug: slug, config }),
    buildDiscordAnnouncement({ config }),
    buildChecklist({ config, slug, namespace, datapackFileName, validation }),
    // re-importable snapshot of this event — drop it back into the Forge to edit/re-run later
    { path: "event_config.json", contents: toPortableEvent(config), kind: "readme", label: "event_config.json" },
  ];

  const bundle: Bundle = {
    slug,
    title: config.title,
    namespace,
    packFormat: config.packFormat,
    files: [...datapackFiles, ...sideCars],
  };

  return { bundle, validation, datapackFileName };
}
