import type { Bundle, GeneratedFile } from "../datapack/types";
import type { ValidationResult } from "../datapack/validate";
import type { EventConfig } from "./types";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { buildSpawnFiles } from "../datapack/spawns";
import { buildRewardFunction } from "../datapack/mcfunction";
import { buildLegendaryFiles } from "./legendary";
import { buildLifecycleFiles } from "./lifecycle";
import { validateDatapack } from "../datapack/validate";
import { buildBountiesFile } from "./bounties";
import { buildDiscordAnnouncement } from "./discord";
import { buildChecklist } from "./checklist";

export interface GenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  /** Suggested .zip file name for the datapack. */
  datapackFileName: string;
}

/**
 * The single entry point: EventConfig in, full file bundle + validation out.
 *
 * Order matters for the checklist, which embeds the validation result and the
 * datapack file name, so we build datapack files first, validate, then build the
 * human-facing side-cars.
 */
export function generateEvent(config: EventConfig): GenerateResult {
  const slug = toId(config.title || "untitled_event");
  const namespace = toNamespace(config.title || "owner_event");

  // --- datapack files ---
  const datapackFiles: GeneratedFile[] = [];
  datapackFiles.push(
    buildPackMeta({
      description: `${config.title} — generated by Cobbleverse Event Forge`,
      packFormat: config.packFormat,
    }),
  );
  datapackFiles.push(
    ...buildSpawnFiles({
      namespace,
      eventSlug: slug,
      weather: config.weather,
      featured: config.featured,
    }),
  );
  datapackFiles.push(
    buildRewardFunction({
      namespace,
      eventSlug: slug,
      eventTitle: config.title,
      rewards: config.rewards,
    }),
  );
  datapackFiles.push(
    ...buildLegendaryFiles({
      namespace,
      eventSlug: slug,
      trigger: config.legendaryTrigger,
      enableFlag: config.pack.enableFlag,
    }),
  );
  // lifecycle (load / uninstall / tick + tags) — centralized so there's one
  // load.json and tick.json only ever appears when explicitly enabled.
  const serverWideLegendary =
    config.legendaryTrigger.enabled &&
    config.legendaryTrigger.legendary.trim() !== "" &&
    config.legendaryTrigger.scope === "server-wide";
  datapackFiles.push(
    ...buildLifecycleFiles({
      namespace,
      slug,
      title: config.title,
      options: config.pack,
      serverWideLegendary,
    }),
  );

  const validation = validateDatapack(datapackFiles);
  const datapackFileName = `${slug}.zip`;

  // --- side-car files ---
  const sideCars: GeneratedFile[] = [
    buildBountiesFile({ eventSlug: slug, config }),
    buildDiscordAnnouncement({ config }),
    buildChecklist({ config, slug, namespace, datapackFileName, validation }),
  ];

  const bundle: Bundle = {
    slug,
    title: config.title,
    namespace,
    packFormat: config.packFormat,
    files: [...datapackFiles, ...sideCars],
  };

  return { bundle, validation, datapackFileName };
}
