import type { Bundle, GeneratedFile } from "../datapack/types";
import type { ValidationResult } from "../datapack/validate";
import type { CrateConfig } from "./types";
import { toId, toNamespace } from "../datapack/sanitize";
import { buildPackMeta } from "../datapack/packMeta";
import { buildCrateLootTable } from "../datapack/lootTable";
import { validateDatapack } from "../datapack/validate";
import { buildOpenFunction } from "./openFunction";
import { buildKeyFiles, keyAdvancementId } from "./usableKey";
import { buildCrateSummary } from "./summary";

export interface CrateGenerateResult {
  bundle: Bundle;
  validation: ValidationResult;
  datapackFileName: string;
}

/** CrateConfig in → loot-table datapack + open-function + summary out. */
export function generateCrate(config: CrateConfig): CrateGenerateResult {
  const slug = toId(config.title || "untitled_crate");
  const namespace = toNamespace(config.title || "owner_crate");

  const keyOn = config.key.enabled;
  const datapackFiles: GeneratedFile[] = [
    buildPackMeta({
      description: `${config.title} — generated by Cobbleverse Event Forge`,
      packFormat: config.packFormat,
    }),
    buildCrateLootTable({ namespace, slug, tiers: config.tiers }),
    buildOpenFunction({
      namespace,
      slug,
      title: config.title || "Crate",
      // re-arm the key advancement so the item can be reused
      revokeAdvancement: keyOn ? keyAdvancementId(namespace, slug) : undefined,
    }),
  ];
  datapackFiles.push(
    ...buildKeyFiles({
      namespace,
      slug,
      title: config.title,
      key: config.key,
      packFormat: config.packFormat,
      openFunctionId: `${namespace}:open_${slug}`,
    }),
  );

  const validation = validateDatapack(datapackFiles);

  const sideCars: GeneratedFile[] = [buildCrateSummary({ config, namespace, slug })];

  const bundle: Bundle = {
    slug,
    title: config.title,
    namespace,
    packFormat: config.packFormat,
    files: [...datapackFiles, ...sideCars],
  };

  return { bundle, validation, datapackFileName: `${slug}.zip` };
}
